version: "3"
services:
  db:
    container_name: mariadb
    build: ./app/database
    restart: always
    ports:
      - "3306:3306"
  api:
    container_name: api
    build: ./app/api
    restart: always
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "3000:3000"
  generate:
    container_name: generate
    build: ./app/scripts/generate
    restart: always
    depends_on:
      - db
    env_file:
      - .env
  # server:
  #   container_name: server
  #   build: ./server
  # collect:
  #   container_name: collect
  #   build: ./scripts/collect
